type Role = 'ADMIN' | 'MANAGER' | 'DOCTOR' | 'NURSE' | 'FAMILY_MEMBER' | 'DEFAULT_USER'
export type Permission =
  | 'CREATE_USER' | 'READ_USER' | 'UPDATE_USER' | 'DELETE_USER' | 'PROMOTE_USER_TO_EMPLOYEE'
  | 'MANAGE_EMPLOYEES' | 'READ_ALL_EMPLOYEES' | 'READ_ALL_NURSES' | 'READ_ALL_DOCTORS' | 'READ_ALL_MANAGERS'
  | 'PRESCRIBE_MEDICATION' | 'VIEW_REPORTS' | 'MANAGE_RESIDENTS' | 'VIEW_RESIDENTS' | 'CREATE_FAMILY_MEMBER'
  | 'MANAGE_HEALTH_RECORDS' | 'MANAGE_ACTIVITIES' | 'VIEW_RESIDENT_RECORDS'
  | 'MANAGE_INCIDENTS' | 'VIEW_INCIDENTS'
  | 'MANAGE_CARE_PLANS' | 'VIEW_CARE_PLANS'

const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMIN: [
    'CREATE_USER', 'READ_USER', 'UPDATE_USER', 'DELETE_USER', 'PROMOTE_USER_TO_EMPLOYEE',
    'MANAGE_EMPLOYEES', 'READ_ALL_EMPLOYEES', 'READ_ALL_NURSES', 'READ_ALL_DOCTORS', 'READ_ALL_MANAGERS',
    'PRESCRIBE_MEDICATION', 'VIEW_REPORTS', 'MANAGE_RESIDENTS', 'VIEW_RESIDENTS', 'CREATE_FAMILY_MEMBER',
    'MANAGE_HEALTH_RECORDS', 'MANAGE_ACTIVITIES', 'VIEW_RESIDENT_RECORDS',
    'MANAGE_INCIDENTS', 'VIEW_INCIDENTS',
    'MANAGE_CARE_PLANS', 'VIEW_CARE_PLANS',
  ],
  MANAGER: [
    'READ_USER', 'UPDATE_USER',
    'MANAGE_EMPLOYEES', 'READ_ALL_EMPLOYEES', 'READ_ALL_NURSES', 'READ_ALL_DOCTORS', 'READ_ALL_MANAGERS',
    'VIEW_REPORTS', 'MANAGE_RESIDENTS', 'VIEW_RESIDENTS', 'CREATE_FAMILY_MEMBER',
    'MANAGE_HEALTH_RECORDS', 'MANAGE_ACTIVITIES', 'MANAGE_INCIDENTS', 'MANAGE_CARE_PLANS',
  ],
  DOCTOR: [
    'READ_USER', 'PRESCRIBE_MEDICATION', 'MANAGE_HEALTH_RECORDS', 'MANAGE_ACTIVITIES',
    'READ_ALL_DOCTORS', 'VIEW_RESIDENTS', 'MANAGE_INCIDENTS', 'MANAGE_CARE_PLANS',
  ],
  NURSE: [
    'READ_USER', 'MANAGE_HEALTH_RECORDS', 'MANAGE_ACTIVITIES',
    'READ_ALL_NURSES', 'VIEW_RESIDENTS', 'MANAGE_INCIDENTS', 'MANAGE_CARE_PLANS',
  ],
  FAMILY_MEMBER: ['VIEW_RESIDENT_RECORDS', 'VIEW_INCIDENTS', 'VIEW_CARE_PLANS'],
  DEFAULT_USER: ['READ_USER'],
}

export function hasPermission(role: string | null, permission: Permission): boolean {
  if (!role) return false
  return ROLE_PERMISSIONS[role as Role]?.includes(permission) ?? false
}

export function hasAnyPermission(role: string | null, permissions: Permission[]): boolean {
  return permissions.some((p) => hasPermission(role, p))
}
